version: '3.8'
services:
  postgres:
    container_name: postgres
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg-notify-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: server
    image: 'node:16-alpine'
    build: ./
    tty: true
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - PGUSER=pguser
      - PGPASSWORD=password
      - PGDATABASE=pg-notify-db
      - PGHOST= localhost
    volumes:
      - ./server:/server
      - /server/node_modules
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata: 
  node_modules:
